// blog-data.jsx — Blog post content & metadata
// ─────────────────────────────────────────────────────────────
// All blog post content lives here so screen components stay lean.
/* ============================================================
   Blog post data (unchanged)
   ============================================================ */
const BLOG_POSTS = [
  {
    id: "ring-road",
    tag: "Featured",
    cat: "Route",
    date: "June 3, 2026",
    readTime: "11 min read",
    author: "Sigríður Björnsdóttir",
    authorRole: "Local guide & travel writer",
    title: "7 Days on the Ring Road: A First-Timer's Honest Account",
    excerpt: "From Reykjavík to Jökulsárlón and back — what we wished we'd known before renting a 4×4 and heading into the unknown.",
    heroSlot: "blog-featured",
    heroPlaceholder: "Ring Road hero — Icelandic landscape panorama",
    relatedCarCat: "SUV",
    ctaTitle: "Ready to drive the Ring Road?",
    ctaDesc: "Most travellers pair this route with a 4×4 SUV. Free cancellation, CDW included.",
    midCtaAfter: 3,
    sections: [
      { type: "intro", body: "We booked a white Toyota RAV4 from Keflavík Airport at 08:00 on a Tuesday in early June. By 09:30 we were already past Selfoss, heading east, with the whole Ring Road in front of us and exactly zero idea what we were doing. Seven days later we returned the car, muddy, exhausted, and ready to go back." },
      { type: "h2", text: "Day 1–2: The South Coast" },
      { type: "body", body: "The South Coast is Iceland 101 — Seljalandsfoss, Skógafoss, the black sand of Reynisfjara, and if you're lucky, a puffin or twelve. It's deservedly popular, which means it's also deservedly crowded in summer. Leave early. We left Reykjavík at 07:00 on day one and had Seljalandsfoss to ourselves for 20 golden minutes before the first tour bus arrived.\n\nThe road surface on Route 1 here is excellent. You don't need a 4×4 for the south coast — but you'll be glad you have one the moment you turn onto any of the F-roads later in the trip." },
      { type: "img", slot: "blog-ring-road-south", placeholder: "South Coast — black sand beach, Reynisfjara", caption: "Reynisfjara beach. Arrive before 9am or after 7pm to beat the crowds." },
      { type: "h2", text: "Day 3: Skaftá and the Glacier Lagoon" },
      { type: "body", body: "Jökulsárlón is the payoff. After two days of waterfalls and basalt columns, the glacier lagoon hits differently. Icebergs the size of houses, some striped with volcanic ash from centuries of eruptions, drifting silently toward the sea. We spent four hours there — two more than planned.\n\nThe drive from Vík to Jökulsárlón is roughly 200 km on Route 1, mostly flat and straight. The road cuts through Skaftá, where a volcanic eruption in 1783 changed the course of European history. There's a small museum worth the stop." },
      { type: "pull", text: "Icebergs the size of houses, some striped with volcanic ash from centuries of eruptions, drifting silently toward the sea." },
      { type: "h2", text: "Day 4–5: The East Fjords" },
      { type: "body", body: "The East Fjords are Iceland's best-kept secret. No glaciers, fewer waterfalls, but the driving is extraordinary — single-track roads snaking up fjord walls, reindeer crossing at dusk, fishing villages that look unchanged since the 1970s. We slept in a tiny guesthouse in Djúpivogur for €80 including breakfast.\n\nOne practical note: petrol stations are sparse here. Fill up in Höfn before heading north. The next reliable station is in Egilsstaðir, 100 km away." },
      { type: "h2", text: "Day 6: Mývatn and the North" },
      { type: "body", body: "Mývatn deserves more than a single day but we gave it one anyway. The pseudo-craters at Skútustaðagígar, the lava formations at Dimmuborgir, the geothermal baths at the Nature Baths — all within 30 minutes of each other. The midges are real. Bring a head net." },
      { type: "img", slot: "blog-ring-road-north", placeholder: "Mývatn — volcanic crater lake, north Iceland", caption: "Mývatn at midnight. The midnight sun makes timing irrelevant — and everything magical." },
      { type: "h2", text: "Day 7: Back to Reykjavík" },
      { type: "body", body: "We finished the Ring Road and couldn't resist adding Þingvellir and Geysir on the way back. Strokkur erupting every five minutes in the low summer sun is impossible to skip.\n\nFinal car stats: 2,180 km over seven days. One puncture near Höfn. Zero regrets." },
      { type: "h2", text: "What we wish we'd known" },
      { type: "list", items: ["Book accommodation months in advance for June and July.", "The weather changes every 20 minutes. Pack layers even on sunny days.", "Speed cameras are everywhere. Iceland takes its 90 km/h limit seriously.", "Gravel F-roads need a 4×4. Not just recommended — legally required.", "The road.is app is essential for daily updates.", "Budget €60–80/day for petrol."] },
    ],
    relatedPosts: ["highland-f-roads", "ev-charging", "packing-june"],
  },
  {
    id: "highland-f-roads",
    tag: "Off-Road",
    cat: "Off-Road",
    date: "May 28, 2026",
    readTime: "6 min read",
    author: "Björn Sigurðsson",
    authorRole: "Off-road driving instructor",
    title: "F-Roads & the Highlands: Which 4×4 Do You Actually Need?",
    excerpt: "When to go, which 4×4 you need, and the five highland routes that reward the adventurous driver.",
    heroSlot: "blog-highland-hero",
    heroPlaceholder: "Highland F-road — river crossing, Landmannalaugar",
    relatedCarCat: "4x4",
    ctaTitle: "Heading into the highlands?",
    ctaDesc: "Book a high-clearance 4×4 with free cancellation — from €58/day.",
    midCtaAfter: 2,
    sections: [
      { type: "intro", body: "Iceland has roughly 7,000 km of F-roads — tracks that carve through lava fields, cross glacial rivers, and climb to passes where the wind genuinely tries to remove your car door. Driving them is the best thing you can do in Iceland. It is also the fastest way to ruin a rental car if you don't respect a few basic rules." },
      { type: "h2", text: "The golden rule: minimum clearance of 22 cm" },
      { type: "body", body: "F-roads are legally off-limits to 2WD vehicles. Not advisory — it's Icelandic law, and rental insurance is void if you drive an F-road in an unsuitable car. The minimum you need is a high-clearance 4×4: a Dacia Duster, Suzuki Jimny, or Toyota RAV4 will handle most F-roads. For the serious ones — F26, F88, F910 — you want a Defender or a Hilux." },
      { type: "pull", text: "Rental insurance is void if you drive an F-road in an unsuitable car. This is Icelandic law, not a recommendation." },
      { type: "h2", text: "The five F-roads worth the detour" },
      { type: "list", items: ["F35 Kjölur — the most accessible highland route. Good for first-timers.", "F208 Fjallabak — past Landmannalaugar and its rhyolite mountains.", "F26 Sprengisandur — Iceland's wild interior crossing. Requires experience.", "F88 to Askja — ends at a caldera lake you can swim in.", "F910 Öskjuvatn — the highest point accessible by car."] },
      { type: "img", slot: "blog-highland-crossing", placeholder: "River crossing on F208, highlands of Iceland", caption: "River crossings: enter perpendicular, drive slow and steady, never stop in the middle." },
      { type: "h2", text: "When do F-roads open?" },
      { type: "body", body: "F-roads are closed in winter — most open between mid-June and early July, depending on snowmelt. Check road.is daily during the opening window. F35 Kjölur typically opens first; Sprengisandur and the northern routes last. They close again in late September.\n\nDriving a closed F-road voids your insurance entirely and risks a fine." },
    ],
    relatedPosts: ["ring-road", "packing-june", "ev-charging"],
  },
  {
    id: "ev-charging",
    tag: "Electric Travel",
    cat: "Electric",
    date: "May 20, 2026",
    readTime: "5 min read",
    author: "María Eiríksdóttir",
    authorRole: "EV travel specialist",
    title: "Driving Iceland in an EV: Charging on the Ring Road",
    excerpt: "We mapped every fast charger on Route 1 so you can plan your Tesla or ID.4 trip with zero range anxiety.",
    heroSlot: "blog-ev-hero",
    heroPlaceholder: "Tesla Model 3 charging at an Icelandic fast charger",
    relatedCarCat: "Electric",
    ctaTitle: "Go electric in Iceland",
    ctaDesc: "Tesla Model 3 and VW ID.4 available — fast-charge capable, AWD.",
    midCtaAfter: 2,
    sections: [
      { type: "intro", body: "Driving an EV around Iceland's Ring Road is no longer an adventure in logistics — it's genuinely straightforward. As of June 2026, there are 43 fast chargers along or just off Route 1, most of them 50–150 kW DC units that will top you up while you eat lunch." },
      { type: "h2", text: "The charger map" },
      { type: "body", body: "The densest coverage is between Reykjavík and Vík (about 190 km) — you'll pass six fast chargers. The longest gap on the whole Ring Road is between Höfn and Egilsstaðir, at roughly 270 km. A Tesla Model 3 Long Range handles this comfortably even in cold weather; an ID.4 will want to top up in Höfn before setting off.\n\nN1 stations are the most reliable network — their 150 kW chargers work with CCS (ID.4, most European EVs) and Tesla's CCS adapter." },
      { type: "img", slot: "blog-ev-charger", placeholder: "DC fast charger at N1 station, South Iceland", caption: "N1 fast chargers accept CCS2 and can charge an ID.4 from 20% to 80% in under 40 minutes." },
      { type: "pull", text: "The longest gap on the Ring Road is 270 km. A Tesla Model 3 Long Range handles it comfortably — the ID.4 will want to top up beforehand." },
      { type: "h2", text: "Cold weather and range" },
      { type: "body", body: "June is the kindest month for EV range in Iceland — temperatures stay above 8°C and cabin heating rarely drops range more than 10–15%. October visits are a different matter; we saw 30% range reduction in sustained cold and wind.\n\nTip: pre-condition the battery before leaving your charger stop. In a Tesla this is automatic if you set a Supercharger as your next destination." },
      { type: "h2", text: "Charging costs" },
      { type: "body", body: "Electricity in Iceland is cheap — geothermal power means you pay about €0.08–0.12 per kWh at most DC chargers. A full charge for a Tesla Model 3 (82 kWh battery) costs roughly €8–10. Compare that to €60–80 in petrol for the same distance in a diesel 4×4." },
    ],
    relatedPosts: ["ring-road", "highland-f-roads", "packing-june"],
  },
  {
    id: "packing-june",
    tag: "Packing Tips",
    cat: "Practical",
    date: "May 12, 2026",
    readTime: "3 min read",
    author: "Anna Halldórsdóttir",
    authorRole: "Iceland Express team",
    title: "What to Pack for an Icelandic Road Trip in June",
    excerpt: "Layers, waterproofs and a good playlist. The essentials (and the things most people forget).",
    heroSlot: "blog-packing-hero",
    heroPlaceholder: "Packed car boot ready for Icelandic road trip",
    relatedCarCat: "SUV",
    ctaTitle: "Your car, sorted",
    ctaDesc: "Book with GPS, WiFi hotspot and camping kit — all in one go.",
    midCtaAfter: 2,
    sections: [
      { type: "intro", body: "June in Iceland is magical — midnight sun, open F-roads, puffins on the cliffs. It's also 8°C with horizontal rain at least once a day. Here's what actually belongs in your bag." },
      { type: "h2", text: "Clothing: the layer system" },
      { type: "list", items: ["Base layer × 3 (merino wool, not cotton)", "Mid-layer fleece × 2", "Waterproof outer shell — jacket and trousers", "Insulated down jacket for evenings", "Warm hat and gloves (yes, in June)", "Hiking boots, waterproof."] },
      { type: "h2", text: "Kit for the car" },
      { type: "body", body: "Your rental already comes with a spare tyre and emergency triangle. Add these yourself:" },
      { type: "list", items: ["Phone mount for the dashboard", "Portable power bank — USB-C, 20,000 mAh", "A physical map of Iceland", "Reusable water bottles — tap water is glacier-pure", "Cash (ISK) — some farm stops don't take cards", "Insect head net if you're going near Mývatn"] },
      { type: "pull", text: "Bring a physical map of Iceland. Mobile signal disappears in the highlands — and Google Maps doesn't know about river crossings." },
      { type: "img", slot: "blog-packing-gear", placeholder: "Laid-out gear — layers, boots, camera, map of Iceland", caption: "Everything you need, none of what you don't. Overpacking is the main rookie error." },
      { type: "h2", text: "What to skip" },
      { type: "body", body: "Formal clothes. A full-size suitcase (soft bags stack better in a 4×4 boot). Flip-flops as your primary footwear. And a selfie stick — Iceland will make you put the phone down anyway." },
    ],
    relatedPosts: ["ring-road", "highland-f-roads", "ev-charging"],
  },
];

const POST_MAP = Object.fromEntries(BLOG_POSTS.map((p) => [p.id, p]));
const BLOG_CATS = ["All", "Route", "Off-Road", "Electric", "Practical"];


Object.assign(window, { BLOG_POSTS, POST_MAP, BLOG_CATS });